# Arabic Translation for Video DownloadHelper
#
# -----------------------------------------------------
# This file provides the full Arabic localization for
# Video DownloadHelper (Addon + Web Interface)
# -----------------------------------------------------

[addon]

Video DownloadHelper description. 132 characters max.
appDesc = "تنزيل الفيديوهات من الويب."

Global strings
restore_purchase_button = "استعادة الشراء"
get_premium_button = "احصل على بريميوم"
back = "رجوع" # زر الرجوع - في لوحة الإعدادات مثلاً
rm_notifications_all = "تجاهل جميع الإشعارات"

Strings for the main panel
waiting_for_media = "في انتظار الوسائط..."
nomedia_title = "لا ترى الوسائط التي تبحث عنها؟"
nomedia_description = "شغّل الفيديو (وتخطّ الإعلانات إن وجدت) للمساعدة في اكتشاف الوسائط. أو أبلغ عن وسائط مفقودة."
nomedia_reload_button = "فرض الكشف"
nomedia_reload_button_tooltip = "فرض إعادة تحميل الصفحة (مسح ملفات تعريف الارتباط)"
show_nomedia_button = "لا يوجد فيديو؟"
show_nomedia_button_tooltip = "انقر هنا إذا لم تتمكن من العثور على الفيديو الخاص بك"
setting_button_tooltip = "الإعدادات"
history_button_tooltip = "إظهار سجل التنزيل"
show_all_history_button = "عرض الكل"
complete_title = "مكتمل"
hide_complete_button = "إخفاء"
translate_button_tooltip = "ساعد في ترجمة VDH"
help_button_tooltip = "مساعدة"

Downloaded media box
open_source_tab_button_tooltip = "فتح علامة التبويب المصدر"
retry_download_button_tooltip = "إعادة محاولة التنزيل"
delete_file_button_tooltip = "حذف الملف"
download_directory_button_tooltip = "إظهار مجلد التنزيل"
clear_downloaded_tooltip = "مسح التنزيلات المكتملة"
show_in_popup_button_tooltip = "إظهار في النافذة المنبثقة"
show_in_sidebar_button_tooltip = "إظهار في الشريط الجانبي"
video_not_playing_button_tooltip = "الفيديو لا يعمل؟"
play = "تشغيل"
warn_drm_tooltip = "تم اكتشاف DRM"

Strings for the settings panel.
version_title = "الإصدار"
account_title = "الحساب"
one_hundred_downloads_title = "لقد قمت بتنزيل 100 فيديو!"
leave_review_description = "نأمل أن تستمتع بـ Video DownloadHelper :) هل تمانع في كتابة مراجعة لطيفة على موقع الإضافة؟"
leave_review_button = "اترك مراجعة"
account_status = "الحالة"
account_status_premium = "بريميوم ($1)"
free_account = "الخطة المجانية"
copy_to_clipboard = "نسخ المعلومات إلى الحافظة"
my_account_button = "حسابي"
download_title = "التنزيلات"
show_notification = "إظهار إشعار عند اكتمال التنزيل"
max_parallel_downloads = "الحد الأقصى للتنزيلات المتزامنة"
saveas_detected_warning = "لقد اكتشفنا أن متصفحك يعرض مربع حوار 'حفظ باسم' بمجرد اكتمال التنزيل. نوصي بتعطيل هذا الخيار في إعدادات المتصفح الخاص بك."
change_saveas_setting = "تغيير الإعداد"
download_directory_title = "دليل التنزيل"
download_directory_description = "يتم تنزيل مقاطع الفيديو في دليل التنزيل الافتراضي للمتصفح. يمكنك أيضًا تحديد مجلد فرعي. يمكن تعيين أدلة تنزيل خاصة بكل موقع باستخدام أداة التسمية الذكية."
change_browser_download_directory = "تغيير دليل تنزيل المتصفح"
bad_download_subdirectory_warning = "المجلد الفرعي الذي حددته غير صالح."
download_subdirectory = "مجلد فرعي للتنزيل"

private_browsing_title = "التصفح الخاص"
private_browsing_warning = "Video DownloadHelper غير مفعل في نوافذ التصفح الخاص/مجهول الهوية. تحتاج إلى تشغيل هذا الخيار يدويًا (هذا غير مطلوب)."
private_browsing_notifications = "إظهار إشعار للتنزيلات الخاصة"
private_browsing_button = "تغيير إعداد التصفح الخاص"
throttle_youtube = "تقييد YouTube (تنزيل أبطأ، لكن أقل عرضة للحظر)"
prefer_original_audio = "تفضيل الصوت الأصلي" # Firefox only
settings_history_title = "السجل"
transient_history_description = "عرض التنزيلات المكتملة في اللوحة"
history_limit = "نسيان سجل التنزيل بعد X يومًا"
appearance_title = "المظهر"
theme_title = "السمة"
theme_light = "فاتح"
theme_dark = "داكن"
theme_system = "النظام"
popup_size_title = "حجم النافذة"
popup_size_small = "صغير"
popup_size_medium = "متوسط"
popup_size_big = "كبير"
font_size_title = "حجم الخط"
font_size_default = "افتراضي"
font_size_large = "كبير"
font_size_verylarge = "كبير جدًا"
panel_position_title = "موضع اللوحة"
use_popup = "إظهار في نافذة منبثقة"
use_sidebar = "إظهار في الشريط الجانبي"
behavior_title = "السلوك"
controls_title = "عناصر التحكم"
show_in_context_menu = "الوصول إلى الأوامر من النقر بزر الماوس الأيمن في الصفحة"
restart_addon = "إعادة تحميل الإضافة"
reset_settings = "إعادة تعيين الإعدادات"
prefered_quality = "جودة الفيديو المفضلة"
prefered_quality_highest = "الأعلى (تنزيل بطيء، دقة عالية)"
prefered_quality_1080p = "1080p (جودة افتراضية جيدة)"
prefered_quality_720p = "720p (تنزيل سريع، دقة منخفضة)"
prefered_quality_480p = "480p (تنزيل أسرع، دقة أقل)"
prefer_mkv = "تنزيل بصيغة MKV عند الإمكان"
preview_mode_title = "معاينة الوسائط"
preview_mode_none = "معطل"
preview_mode_video = "معاينة فيديو قصيرة"
preview_mode_image = "صورة"
media_discovered_ordering_title = "استراتيجية ترتيب الوسائط"
order_media_smart = "ذكي (موصى به)"
order_media_by_newest = "الأحدث أولاً"
order_media_by_oldest = "الأقدم أولاً"

String for history page
history_title = "سجل التنزيل"
history_warning = "نحن لا نسجل سجل التنزيلات الخاص بك. هل تريد أن يتذكر Video DownloadHelper سجل التنزيلات الخاص بك؟"
history_warning_2 = "لا تقلق، كل شيء يبقى على جهازك. نحن نقدر خصوصيتك."
enable_history = "تمكين السجل"
clear_history = "مسح السجل"
disable_history = "لا تتذكر سجلي"
no_downloads_yet = "لا توجد إدخالات بعد."

Various notifications
download_failed = "فشل التنزيل"
download_failed_description = "للأسف فشلنا في تنزيل هذه الوسائط المحددة. نحاول دعم أكبر عدد ممكن من المواقع، لذا سيساعد كثيرًا إذا تمكنت من الإبلاغ عن هذا الخطأ (إنه مجهول!)."
download_interrupted = "تمت مقاطعة التنزيل"
download_interrupted_description = "تمكنا من تنزيل ملفك، ولكن كانت هناك مشكلة في الشبكة، لذلك قد يكون الملف أقصر من المتوقع. نحاول دعم أكبر عدد ممكن من المواقع، لذا سيساعد كثيرًا إذا تمكنت من الإبلاغ عن هذه المشكلة (إنها مجهولة!)."
download_with_drm_failed_description = "حدث خطأ ما. ونعتقد أن هذا الفيديو به DRM. نحن لا ندعم مقاطع الفيديو التي تحتوي على DRM."
no_youtube = "التنزيل من youtube غير مسموح به"
no_youtube_description = "لسوء الحظ، لا يسمح متجر Chrome الإلكتروني بإضافات لتنزيل فيديوهات YouTube، لذلك لم نتمكن من تضمين هذه الميزة في إصدار Chrome من الإضافة."
no_youtube_description_2 = "يرجى استخدام Firefox أو Microsoft Edge"
premium_required = "حالة بريميوم مطلوبة"
premium_yt_required_description = "بدون حالة Premium، لا يمكن إجراء تنزيل YouTube إلا بعد ساعتين من التنزيل السابق."
premium_hls_required_description = "بدون حالة Premium، لا يمكن إجراء تنزيل HLS أو MPD إلا بعد ساعتين من التنزيل السابق."
premium_all_required_description = "بدون حالة Premium، لا يمكن إجراء التنزيل إلا بعد ساعتين من التنزيل السابق."
youtube_too_many_downloads = "عذرًا، يبدو أن YouTube محظور"
youtube_too_many_downloads_description = "قد يحد YouTube أحيانًا من عدد مقاطع الفيديو التي يمكن طلبها. للأسف لا يمكننا فعل شيء حيال ذلك. حاول مرة أخرى لاحقًا."

Downloading media box
stop = "إيقاف"
cancel = "إلغاء"

Media we found in the page
copy_url = "نسخ الرابط" # In menu and as a button
always_copy_url = "نسخ الرابط دائمًا"
download_button = "تنزيل"
download_as_button_and_menu = "تنزيل باسم…"
rename_short = "إعادة تسمية" # Keep this as short as possible

always_download_as_menu = "تنزيل دائمًا باسم…"
download_audio_button = "صوت"
download_audio_and_video_menu = "تنزيل الصوت والفيديو"
download_audio_only_menu = "تنزيل الصوت فقط"
audio_only_for_this_website = "صوت دائمًا فقط لهذا الموقع"
details = "تفاصيل"

Report buttons
report = "إبلاغ"
reporting = "جاري الإبلاغ…"
reported_thankyou = "شكرًا لك!"

[web]

back = "رجوع" # Go back button

On top of all pages.
header_help = "مساعدة"
header_ask_question = "اسألنا سؤالاً"

Context: activation page after receiving the magic link via email.
activate_title = "تفعيل" # hope it crashes
activate_pending = "قيد الانتظار…"
activate_success = "نجاح"
activate_error = "خطأ"
activate_no_addon_found = "لم يتم العثور على إضافة. هل الإضافة مثبتة؟"
activate_no_method_found = "لم يتم العثور على طريقة."
activate_help_me = "ساعدني."

Context: webpage to restore a purchase, which require the user to enter their email.
issue_title = "استعادة الشراء"
issue_submit = "إرسال"
issue_thank_you = "شكرًا لك"
issue_enter_email = "لاستعادة عملية الشراء، أدخل عنوان البريد الإلكتروني الذي استخدمته لشراء ترخيصك:"
issue_email_sent = "لقد أرسلنا لك للتو بريدًا إلكترونيًا به رابط سيقوم بتنشيط منتجك."
issue_or_digit = "أو يمكنك أيضًا إدخال الرمز المكون من 6 أرقام الذي أرسلناه إليك:"
issue_just_digit = "أدخل الرمز المكون من 6 أرقام الذي أرسلناه إليك:"
issue_i_have_a_code = "(انقر هنا إذا كان لديك رمز بالفعل)"
issue_i_have_a_key = "(انقر هنا إذا كان لديك مفتاح ترخيص)"
issue_key = "أدخل مفتاح ترخيص Video DownloadHelper الخاص بك:"

Context: this page - https://downloadhelper.net/
landing_text1 = "قم بتنزيل أي فيديو من أي موقع، إنه يعمل فقط!"
landing_text2 = "أكثر من 1000 موقع مدعوم"
landing_text3 = "موثوق به من قبل 7 ملايين مستخدم"
landing_text4 = "تقييم 4.5 نجوم على متجر الإضافات"
landing_install_for_google = "تثبيت لـ Chrome"
landing_install_for_mozilla = "تثبيت لـ Firefox"
landing_install_for_microsoft = "تثبيت لـ Edge"
landing_feature1_title = "تنزيل عالي الدقة بأقصى سرعة"
landing_feature1_description = "قم بتنزيل مقاطع الفيديو بدقة عالية، وبأقصى سرعة. نحن نفخر بأننا نمتلك أسرع محرك تنزيل موجود."
landing_feature2_title = "أرشفة الفيديوهات"
landing_feature2_description = "احفظ فيديوهاتك المفضلة في أرشيف، لضمان عدم ترك أي شيء خلفك."
landing_feature3_title = "دعم البث المباشر"
landing_feature3_description = "استمتع بمشاهدة البث المباشر دون اتصال بالإنترنت، متحررًا من قيود الوقت الفعلي."
landing_feature4_title = "تنزيل الصوت"
landing_feature4_description = "استخرج الصوت من مقاطع الفيديو، محولاً إياها إلى MP3 أو بودكاست للاستماع السهل."

Context: this is for a "buy a license" webpage.
premium_hero1 = "ادفع مرة واحدة، استخدم للأبد"
premium_hero2 = "احصل على ترخيص مدى الحياة لـ Video DownloadHelper"
premium_hero3 = "قم بتنزيل أي فيديو بقدر ما تريد، بدون حدود."
premium_supported_payment_methods = "طرق الدفع المدعومة"
premium_buy = "شراء"

Context: the page that opens after the addon gets installed.
welcome_text = "الآن لن يفوتك أي فيديو!"
welcome_pin_message = "ثبّت أيقونة الإضافة على شريط الأدوات الخاص بك:"
